stages:
  - build
  - deploy

variables:
  APP_IMAGE: "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  APP_IMAGE_LATEST: "$IMAGE_NAME:latest"

build_and_push_image:
  stage: build
  tags:
    - gcp-shell
  script:
    - cd "$CI_PROJECT_DIR"
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build -t "$APP_IMAGE" -t "$APP_IMAGE_LATEST" ./app
    - docker push "$APP_IMAGE"
    - docker push "$APP_IMAGE_LATEST"
  only:
    - main

update_gitops_image_tag:
  stage: deploy
  tags:
    - gcp-shell
  script:
    - cd "$CI_PROJECT_DIR"
    - git config user.name "GitLab CI"
    - git config user.email "gitlab-ci@users.noreply.gitlab.com"
    - 'sed -i "s/^    newTag: .*/    newTag: ${CI_COMMIT_SHORT_SHA}/" gitops/newsgenie/kustomization.yaml'
    - 'grep -n "newTag:" gitops/newsgenie/kustomization.yaml'
    - git add gitops/newsgenie/kustomization.yaml
    - |
      if git diff --cached --quiet; then
        echo "No GitOps manifest change detected"
        exit 0
      fi
    - git commit -m "Update NewsGenie image tag to ${CI_COMMIT_SHORT_SHA} [skip ci]"
    - 'git push "https://oauth2:${GITHUB_TOKEN}@github.com/akramsiddiqui2007/newsgenie-cicd.git" HEAD:main'
  only:
    - main
