stages:
  - build
  - deploy

variables:
  APP_IMAGE: "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  APP_IMAGE_LATEST: "$IMAGE_NAME:latest"

build_and_push_image:
  stage: build
  tags:
    - gcp-shell
  script:
    - cd "$CI_PROJECT_DIR"
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build --build-arg APP_BUILD_SHA="$CI_COMMIT_SHORT_SHA" --build-arg APP_BUILD_TIME="$(date -u +'%Y-%m-%d %H:%M:%S UTC')" -t "$APP_IMAGE" -t "$APP_IMAGE_LATEST" ./app
    - docker push "$APP_IMAGE"
    - docker push "$APP_IMAGE_LATEST"
  only:
    - main

deploy_to_gcp_vm:
  stage: deploy
  tags:
    - gcp-shell
  before_script:
    - cd "$CI_PROJECT_DIR"
    - chmod 600 ~/.ssh/newsgenie_oci
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install "ansible-core>=2.16,<2.17"
    - export ANSIBLE_HOST_KEY_CHECKING=False
  script:
    - cd "$CI_PROJECT_DIR"
    - source .venv/bin/activate
    - export OPENAI_API_KEY="$OPENAI_API_KEY"
    - export APP_IMAGE="$APP_IMAGE"
    - ansible-playbook -i ansible/inventory/hosts.yml --private-key ~/.ssh/newsgenie_oci ansible/playbooks/deploy_app.yml
  only:
    - main
