apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newsgenie
  namespace: newsgenie
spec:
  ingressClassName: traefik
  rules:
    - host: app.newsgenie.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: newsgenie
                port:
                  number: 80
