apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: akramsiddiqui/newsgenie
    newName: akramsiddiqui/newsgenie
    newTag: 96aa462e
