ansible_user: akram
ansible_ssh_private_key_file: ~/.ssh/newsgenie_oci
ansible_python_interpreter: /usr/bin/python3

k3s_kubeconfig: /etc/rancher/k3s/k3s.yaml
argocd_namespace: argocd
argocd_install_url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
